spring.application.name=task2_fetch_json_data

spring.datasource.url=jdbc:postgresql://localhost:5432/json_placeholder_data
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true